spring:
    datasource:
        driverClassName: org.h2.Driver
        platform: postgres
        url: jdbc:h2:mem:testdb
        username: sa
        password: password
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
